# ZSH envioronment

export LANG="en_US.UTF-8"
#export TERM='xterm'
export DEFAULT_USER=$USER
export EDITOR='nvim'
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/sbin:$PATH
#
# Cask
export PATH=$HOME/.cask/bin:$PATH

# Golang
export GO111MODULE=auto
export GOPROXY=https://goproxy.io,direct
export GOPATH=$HOME/go
export PATH=${GOPATH//://bin:}/bin:$PATH

# Rust
export PATH=$HOME/.cargo/bin:$PATH
. "$HOME/.cargo/env"

#unset DEBUGINFOD_URLS
#export DEBUGINFOD_CACHE_PATH="$HOME/.cache/debuginfod"
